sudo: required
services:
  - docker

before_install:
  - docker build -t yoshiki1116/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true yoshiki1116/react-test npm test

after_success:
  - docker build -t yoshiki1116/multi-client ./client
  - docker build -t yoshiki1116/multi-nginx ./nginx
  - docker build -t yoshiki1116/multi-server ./server
  - docker build -t yoshiki1116/multi-worker ./worker
  #login docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push docker hub
  - docker push yoshiki1116/multi-client
  - docker push yoshiki1116/multi-nginx
  - docker push yoshiki1116/multi-server
  - docker push yoshiki1116/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: /elasticbeanstalk-us-east-2-994018323562
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
